### PR TITLE
Updated mmvmysql.sh to mysql version 5.6.23

### PR DESCRIPTION
**Pull request by futureFry**
changed download to file mysql-5.6.23-osx10.9-x86_64.dmg.
Still showing 10.8 in the pkg file.

### CODE REVIEW

**Comment by OConnorStP** [comment]
That's odd -- I just ran the script and it installed mysql-5.6.22.  Any ideas?

**Comment by jonschwenn** [comment]
Pull request has not (yet) been merged.  Have not yet tested the 5.6.23 install.  I usually update it ever other version.

**Comment by OConnorStP** [comment]
Ooops.  Sorry about that.  Still learning my way around the GitHub process

**Comment by jonschwenn** [comment]
Updated script to 5.6.24 - closing request.

**Just a reminder - do not re-run the script as a method for updating MySQL**

**Pull request closed without merging**
